### ISSUE TITLE
bucket_endpoint is not exposed in SCC module

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-scc#127]
`ibm_scc_instance_settings` seems to have a [bucket_endpoint](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/scc_instance_settings#bucket_endpoint) option that we are not using in the module. 

The provider documentation is terrible here, but I'm assuming that if not value passed, its defaulting to public endpoint? Can we find this out - we may need to expose the ability for users to override the endpoint if they have public endpoint disabled for buckets.

**Comment by kierramarie** [comment]
Looking into what the default endpoint is

**Comment by kierramarie** [comment]
instance_settings.object_storage.bucket_endpoint is an empty string by default. `"bucket_endpoint" = ""`

**Comment by kierramarie** [comment]
@ocofaigh do you want to expose it?

**Comment by ocofaigh** [comment]
@kierramarie do what endpoint is used to communicate with the COS bucket if its not specified? public, private, direct?

**Comment by kierramarie** [comment]
@ocofaigh it looks like the default is public

**Comment by ocofaigh** [comment]
This will then have to be backported to the SCC DA

**Comment by kierramarie** [comment]
Will do.

**Comment by ocofaigh** [comment]
Seems its an issue with the docs, which is already being tracked here -> https://github.com/IBM-Cloud/terraform-provider-ibm/issues/5110
