### ISSUE TITLE
Support for updating SCC settings when an existing instance is used

### ISSUE THREAD

**Issue by Soaib024** [terraform-ibm-modules/terraform-ibm-scc#141]
### Description

Currently, updating SCC settings are not allowed when using an existing SCC instance because of the following restrictions. https://github.com/terraform-ibm-modules/terraform-ibm-scc/pull/121#issuecomment-2285752549
https://github.com/terraform-ibm-modules/terraform-ibm-scc/blob/de2214be17fc4558134539d6b32a16dff81e00cc/main.tf#L91

### New or affected modules

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by ocofaigh** [comment]
@Soaib024 Had a chat with @in-1911 on this and we agreed that when passing an existing instance, the DA should not configure COS or event notifications
