### ISSUE TITLE
Automate the creation of the attachments of FS Cloud

### ISSUE THREAD

**Issue by lionelmace** [terraform-ibm-modules/terraform-ibm-scc#184]
Today, automating the creation of one attachment requires to pass the `attachment_parameters` such as the following

```
 attachment_parameters {
    parameter_name = "cbr_endpoints_allowed_ip_list"
    parameter_display_name =  "IP allowlist for CBR"
    parameter_type =  "ip_list"
    parameter_value =  "['255.255.255.255/32']"
    assessment_type =  "automated"
    assessment_id =  "rule-b5675539-fb0a-4464-93a3-f9c3ab1da0f8"
  }
```

FS Cloud has 155 attachment_parameters and we need to update those automatically.

**Comment by lionelmace** [comment]
@ocofaigh Let me share an example. In my FS Cloud attachment creation, I had to pass all the parameters.
https://github.com/lionelmace/ibm-cloud-native/blob/main/terraform/security-scc-scan-fscloud.tf

How do you do the lookup for those parameters?

**Comment by ocofaigh** [comment]
@lionelmace Why not use our [attachment module](https://github.com/terraform-ibm-modules/terraform-ibm-scc/tree/main/modules/attachment) to do this. Your using the provider directly here. If you use our module, you only need to pass profile details and it will add the required attachements.

If you wan't to continue to use provider directly, you can take same approach as we do in the module ([here](https://github.com/terraform-ibm-modules/terraform-ibm-scc/blob/721425de131f405bd60f3820e2dbfee08fdaa161/modules/attachment/main.tf#L60)), and do a data lookup to fetch the attachment parameters

**Comment by lionelmace** [comment]
Fantastic! The attachment module is what I was looking for. Thanks @ocofaigh
