### ISSUE TITLE
Could not find a valid profile name

### ISSUE THREAD

**Issue by lionelmace** [terraform-ibm-modules/terraform-ibm-scc#210]
I just faced the following issue

```
Error: Invalid function argument
on .terraform/modules/create_profile_attachment_cis/modules/attachment/main.tf line 38, in locals:
  validate_profile_name = length(local.sorted_list) == 0 ? tobool("Could not find a valid profile name ${var.profile_name}") : true
while calling tobool(v)
var.profile_name is "CIS IBM Cloud Foundations Benchmark v1.1.0"
Invalid value for "v" parameter: cannot convert "Could not find a valid profile name CIS IBM Cloud Foundations Benchmark v1.1.0" to bool; only the strings "true" or "false" are allowed.
```

with the .tf script below
```

module "create_profile_attachment_cis" {
  source                 = "terraform-ibm-modules/scc/ibm//modules/attachment"
  profile_name           = "CIS IBM Cloud Foundations Benchmark v1.1.0"
  profile_version        = "latest"
  scc_instance_id        = ibm_resource_instance.scc_instance.guid
  attachment_name        = format("%s-%s", local.basename, "attachment-cis")
  attachment_description = "profile-attachment-description"
  attachment_schedule    = "daily"
  # scope the attachment to the account
  scope = [{
    environment = "ibm-cloud"
    properties = [
      {
        name  = "scope_type"
        value = "account"
      },
      {
        name  = "scope_id"
        value = local.account_id
      }
    ]
  }]
}
```

Full code is available at https://github.com/lionelmace/ibm-cloud-native/blob/main/terraform/security-scc-scan-attachment.tf

It was working yesterday...

**Comment by ocofaigh** [comment]
@lionelmace You said it was working yesterday, but was it working on the same version of the module?

**Comment by lionelmace** [comment]
Yes I'm positive.

**Comment by ocofaigh** [comment]
Your [code](https://github.com/lionelmace/ibm-cloud-native/blob/main/terraform/security-scc-scan-attachment.tf) is not locked into module version, so how can you be sure?
Can you verify if it happens with [v1.8.23](https://github.com/terraform-ibm-modules/terraform-ibm-scc/releases/tag/v1.8.23)? In `v1.8.24` we added the error handling logic your hitting, so if it passes in previous version we know its related to our module code. If you get an error like `local.sorted_list is empty tuple` we know its an SCC / provider issue.

**Comment by lionelmace** [comment]
Indeed. I'll test Monday morning first thing.

**Comment by ocofaigh** [comment]
@lionelmace the way its working under the hood, the data lookup looks up a list of SCC profiles, and then tries to verify that the profile you listed is a valid profile. So you should only ever get this error if:
a) you provided an incorrect profile name (which is not the case for you)
b) the SCC api didn't return the full list of profiles

Hopefully its not a pagination issue with the api returning the list of profiles - you would hope the provider is handling that. But et us know if you do see it again and we can debug.
