### ISSUE TITLE
Remove the known limitation from the main readme.

### ISSUE THREAD

**Issue by lionelmace** [terraform-ibm-modules/terraform-ibm-scc#42]
The main README.md reference this limitation below. This limitation does not exist any more in the provider 1.63.0.

```
There is currently a known issue with the IBM provider (https://github.com/IBM-Cloud/terraform-provider-ibm/issues/5131) where the provider is always trying to use the us-south endpoint when trying to configure the instance, even if the instance is not in us-south. You will see the following error on apply:
```

**Comment by ocofaigh** [comment]
@lionelmace A new profiles submodule is being added in https://github.com/terraform-ibm-modules/terraform-ibm-scc/pull/30

**Comment by ocofaigh** [comment]
PR opened to remove limitation from docs, and required version 1.63.0 or later -> https://github.com/terraform-ibm-modules/terraform-ibm-scc/pull/47

**Comment by ocofaigh** [comment]
PR merged, please use https://github.com/terraform-ibm-modules/terraform-ibm-scc/releases/tag/v1.1.3
